### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by monkey-cat** [EU-EDPS/website-evidence-collector#28]
Command executed as root
```
# npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/bin/website-evidence-collector -> /usr/lib/node_modules/website-evidence-collector/website-evidence-collector.js
/usr/bin/website-evidence-reporter -> /usr/lib/node_modules/website-evidence-collector/website-evidence-reporter.js

> puppeteer@2.1.1 install /usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-07T22_08_24_938Z-debug.log
```

**Comment by jalemann** [comment]
The steps provided [here](https://github.com/EU-EDPS/website-evidence-collector/issues/5) should fix it.

**Comment by rriemann-eu** [comment]
Please reopen if issue persists after following advice in #5.
